AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda with Bedrock response streaming
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Layers:
      - arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:38
      - arn:aws:lambda:us-east-1:094274105915:layer:AWSLambdaPowertoolsTypeScript:21
    MemorySize: !Ref pFnMemory
    Runtime: nodejs18.x
    Timeout: !Ref pFnTimeout
    Tracing: Active
Parameters:
  pFnMemory:
    Type: Number
  pFnTimeout:
    Type: Number
Resources:
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: cloudwatch-insights
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
        - PolicyName: xray
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                Resource: '*'
        - PolicyName: bedrock
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/*
  Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn.handler
      Role: !GetAtt FnRole.Arn
      FunctionUrlConfig:
        AuthType: AWS_IAM
        InvokeMode: RESPONSE_STREAM
      Environment:
        Variables:
          POWERTOOLS_METRICS_NAMESPACE: LambdaBedrockStreaming
          POWERTOOLS_SERVICE_NAME: test
      Tags:
        application:group: generative-ai
        application:subgroup: bedrock
        application:owner: heeki
  FnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Fn}'
      RetentionInDays: 7
Outputs:
  outFn:
    Value: !Ref Fn
  outFnArn:
    Value: !GetAtt Fn.Arn
  outFnEndpoint:
    Value: !GetAtt FnUrl.FunctionUrl